* Proposition de projet

Proposition de projet de développement dans le cadre du cours 420-G55.

La proposition doit être approuvée par l'enseignant. Par contre, les détails (sauf les membres de l'équipe) sont sujets à changement selon les circonstances au cours du développement avec l'accord de l'enseignant.

** Équipe

- Nom des coéquipiers (3 ou 4 personnes) :
  1 : Nicholson Rainville Jacques
  2 : Teddy Cabrel Ekeu Mbouatchi
  3 : Cristina Candanedo
  4 : Rami Kassan
  
- Horaire de rencontre hebdomadaire (1h) : 

** Projet

- Thématique (quel est le domaine d'application de votre travail) :

L'application permet de faire des réservation de vols. 
  
- Problème à résoudre (du point de vue de l'utilisateur, quel sera la plus-value de votre app) :
L'utilisateur peut accéder à son historique de réservation, voir les vols selon les dâtes
et destination et reserver un vol, gérer ses informations et préférences en matière de voyage.
  
- Analyse comparative (nommez au moins deux applications (Android ou non) déjà existantes qui font plus ou moins la même chose) :
L'application d'Air Transat
L'application d'Air Canada

  
** Fonctionnalités minimales :
- Voir les vols disponibles
- Créer une réservation (choix du vol, de la classe, du siège, du repas)

*** Sauvegarde locale d'informations utilisateurs
Quelles données comptez-vous stoquer localement sur l'appareil? :
- Les préférences en matière de destinations
- Les préférences en matière de repas
- Historique des recherches

*** Échange de données avec un service extérieur
Quelles données comptez-vous échanger avec un service extérieur? :
- Les vols disponibles
- Les réservation : Création, modification, annulation, historique
- Les informations de l'utilisateur et leurs modifications

L'API existe-t-il déjà? :
Si oui, est-il accessible librement? gratuitement? devez-vous l'héberger vous-même? :
- Il s'agit d'une API que nous développons déjà dans le cadre du cours de service d'échange de données 
Si non, sera-t-il développé et par qui? ou simulé? : 
Si déjà connu, de quel type d'API s'agit-il?
  - REST

*** Interaction avec d'autres applications du système Android
Quelle(s) fonctionnalité(s] fer(a|ont) appel à une autre application du système?
(ex.: prise de photo/vidéo, envoie de courriel, ajout de rendez-vous au calendrier, etc.) :
- Interaction avec le calendrier pour ajouter les réservation sur celui-ci


*** Licence choisie :
- ☐ Propriétaire
- Libre
  ☐ GPLv2 : (peut être utilisée au cœur d'un système non-libre)
  ☐ GPLv3 : (ne peut pas être utilisée au cœur d'un système non-libre)
  X MIT : peut être utilisée dans n'importe quelle circonstance
  ☐ Autre, laquelle? :
  ☐ à déterminer
